# Generated by Django 3.1.4 on 2022-10-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kotxeak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=255)),
                ('modeloa', models.CharField(max_length=255)),
                ('matrikula', models.CharField(max_length=7)),
            ],
        ),
    ]
