# Generated by Django 3.1.4 on 2022-10-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alokairuak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertsona_id', models.IntegerField()),
                ('kotxea_id', models.IntegerField()),
                ('hasiera_data', models.CharField(max_length=255)),
                ('amaiera_data', models.CharField(max_length=255)),
            ],
        ),
    ]
